### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mingchuno** [enragedginger/akka-quartz-scheduler#17]
Hi, I am currently using this tools in my own project. Is the maintainer still here? If not, can I help with maintain the project? I saw a PR has not yet been merge for 7 months and I myself have some code to push...

**Comment by mingchuno** [comment]
I have already did some commits in my fork...
https://github.com/mingchuno/akka-quartz-scheduler/commits/master

**Comment by enragedginger** [comment]
Hi mingchuno,

I would not say that the project is dead.  I unfortunately have several other side projects that keep me busy, so I'm not able to devote too much time to this project.  I did, however, review the commits you made.  If you submit a pull request, I will merge them in.

**Comment by mingchuno** [comment]
oh, that's nice. Thank you very much

**Comment by enragedginger** [comment]
Thank you for your contributions!  I've pushed a new build (version 1.4.0) that includes your changes.  I incremented the minor version number because there was a breaking API change that I had to make (unrelated to your changes).  Previously, the library supposedly supported multiple "calendars" per schedule.  However, this feature never worked properly, as best as I can tell, because Quartz only supports one calendar per trigger.  Therefore, the "calendars" Array[String] property on a schedule definition in the conf is now simply an optional "calendar" String property.
