### ISSUE TITLE
Specify end time for a scheduler

### ISSUE THREAD

**Issue by charyorde** [enragedginger/akka-quartz-scheduler#35]
Is it possible to stop a scheduler after x number of times? Or specify an end time?

**Comment by mingchuno** [comment]
normally you won't "end" a cron job. So I think it is not a valid use case that need to add into the project. But still, you can inc a running counter each time when you receive a job message and cancel the timer when count == x, sth like:

```
val x = 10
def receive = _receive(0)

def _receive(count: Int): Receive = {
  case "job" =>
    if count >= x
      timer.cancel()
    else
      context.become(_receive(count+1))
      // do your job
}
```

It is even easier for specify an end time, just check the time now when you receive the job message.

I think those should remain in your business logic instead of the lib.

**Comment by enragedginger** [comment]
Thanks for the explanation, @mingchuno. I agree.
