### ISSUE TITLE
How to unload the scheduler when Play is stopped/reloaded

### ISSUE THREAD

**Issue by ps3331333** [enragedginger/akka-quartz-scheduler#58]
Using the scheduler in Play for Scala, I initiate the scheduler on startup like so:

>          val scheduler = QuartzSchedulerExtension(system)
>          val d = scheduler.schedule("dailyproc", mainEtl, "abc", None)
 
Problem is that I load a table using Hibernate in the scheduler task, and when Play is reloaded due to code change, I get an error saying that classes "cannot be cast" where the class is the same. This happens because the classloaders are different. 

One solution is to unload the scheduler when Play is reloaded, how can this be achieved? I could not find a method to unload the scheduler when Play is stopped/reloaded.

Please see more details [here](https://stackoverflow.com/questions/45748735/object-cannot-be-cast-using-hibernate-in-play-for-scala)

**Comment by enragedginger** [comment]
Hi @ps3331333,

This issue is really more of a Play issue than anything else, I believe, as Play causes this kind of issue with a few different libraries.

Basically, you'll want to use the `ApplicationLifecycle` to manage this. You can read more about that [here](https://www.playframework.com/documentation/2.5.x/PluginsToModules#Create-a-Module-class). Hopefully that helps.
