### ISSUE TITLE
Publish akka 2.5.x scala 2.11 version

### ISSUE THREAD

**Issue by SamTheisens** [enragedginger/akka-quartz-scheduler#64]
Could you please publish a Scala 2.11 and akka 2.5.x compatible version of this library? In my project I can't upgrade to Scala 2.12 yet due to a dependency on Apache Spark.

**Comment by mingchuno** [comment]
@SamTheisens You can try "1.6.0-akka-2.4.x", it should be working too for Scala 2.11 X akka 2.5.x

**Comment by ktoso** [comment]
Hi there, Akka team here, not quite sure why the library includes Akka versions in the version...
Akka 2.5 is strictly backward binary compatible with 2.4.x, which is enforced and documented: doc.akka.io/docs/akka/current/scala/common/binary-compatibility-rules.html

cc @enragedginger was there a specific reason you chose to publish with akka versions in the version here?

**Comment by enragedginger** [comment]
Hi everybody!

@SamTheisens, @mingchuno is right. You should be able to use version `1.6.0-akka-2.4.x`. It was built specifically for Scala 2.11. The only difference between it and the next version is the Scala version.

@ktoso Akka 2.5 is indeed backwards compatible with 2.4. The decision to include the Akka version number in the build number predates my inheritance of this project. Regardless, it does make it slightly easier to debug transitive dependency issues should they ever arise.

**Comment by ktoso** [comment]
Hmm, I see... It's a rather unfortunate versioning scheme since the only version that could affect compatibility is "akka 3" which currently is not even planned to happen any time in the coming years hm.

I guess you'd rather not change the versioning scheme? Though it is a bit misleading as shown by this ticket hm.
If not, then perhaps explaining that "if you need scala 2.11 you can use that version since akka is fully backwards binary compatible [see here]"? in the README would help people? I'd link to here doc.akka.io/docs/akka/current/scala/common/binary-compatibility-rules.html then

**Comment by SamTheisens** [comment]
Thanks @enragedginger, I have tried `1.6.0-akka-2.4.x` and I can confirm it works well with Akka 2.5. I agree with @ktoso's suggestion on the README.md, this would have helped me.

**Comment by enragedginger** [comment]
@SamTheisens Thank you for confirming this. Can you submit a PR on the README.md with some text that you think would be helpful for anyone else who might run into this?
