### ISSUE TITLE
Do jobs overlap?

### ISSUE THREAD

**Issue by vuongbason994** [enragedginger/akka-quartz-scheduler#82]
Hi, would like to know if jobs overlap if the previous trigger is still running and exceeds the interval?

**Comment by enragedginger** [comment]
Hi @vuongbason994 jobs will fire on their regularly scheduled intervals. However, by design, Akka actors only process one message at a time, so you won't have to worry about the same job running simultaneously

**Comment by vuongbason994** [comment]
What I meant was that I do not know for sure whether the processing time for the previous batch will exceed the time interval set, hence it is vital that the next trigger will get executed at the fixed intervals whilst any previous jobs continue processing

**Comment by enragedginger** [comment]
@vuongbason994 That's a good question. By design Akka actors only process one message at a time. However, you can set up pools of actors to achieve the desired effect. In this case you could set up a pool / shared mailbox / router on the `ActorSelection` that you pass to this library (or just pass in a ref to a single actor and then route / forward the message to your pool of actors from that single actor).

The Akka docs are a good resource for setting this up: https://doc.akka.io/docs/akka/2.5.4/scala/routing.html

**Comment by vuongbason994** [comment]
Thanks so much again for your kind assistance! I will take a look at the akka docs then :) +1:
